spring:
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2

        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2

        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=2

        - id: users-auth-service
          uri: lb://users-auth-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2