spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: products-service
            uri: lb://products-service
            predicates:
              - Path=/api/products/**
            filters:
              - StripPrefix=2
          - id: orders-service
            uri: lb://orders-service
            predicates:
              - Path=/api/orders/**
            filters:
              - StripPrefix=2